variables:
  GIT_SUBMODULE_FORCE_HTTPS: "true" # rewrite git:// submodule urls to https
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_UPDATE_FLAGS: --jobs 16
  GIT_STRATEGY: clone # fetch is more efficient


include:
  - component: $CI_SERVER_FQDN/CGG-public/ci-components/debian-linux/debian@v0.0.9
    inputs:
      stage: build
      debian_release: trixie
      tags:
        - cgg
        - linux
        - docker-docker
  - component: $CI_SERVER_FQDN/CGG-public/ci-components/windows/vs22-cmake@v0.0.10
    inputs:
      stage: build
      tags:
        - cgg
        - win25
        - docker-windows

