stages:
  - build

gcc-c++11:
  stage: build
  script: "CI/ci-linux.sh gcc C++11"
  tags:
    - Linux

clang-c++11:
  stage: build
  script: "CI/ci-linux.sh clang C++11"
  tags:
    - Linux

gcc-c++14:
  stage: build
  script: "CI/ci-linux.sh gcc C++14"
  tags:
    - Linux

clang-c++14:
  stage: build
  script: "CI/ci-linux.sh clang C++14"
  tags:
    - Linux

